$ANSIBLE_VAULT;1.1;AES256
62373430306634613263616531386234326463373238636531623830313736613732363731373636
3033613963313938333834336563666432383763363330320a643335643061333964353165626537
65316365343963383964653432386231363064323864316333663366666530653462313565393137
6135386162623735310a616465613035303234376463356234396133363765623637333439383737
61326562656633306337393363343930663537356538373563616239303063363535663339353061
6364396138613235386665306561623030653566626564663934
